#!/bin/bash

# Load environment variables from .env file
set -a
source .env
set +a

# Build the environment variables string for gcloud
ENV_VARS="NODE_ENV=production"
ENV_VARS="$ENV_VARS,REDIS_URL=$REDIS_URL"
ENV_VARS="$ENV_VARS,REDIS_HOST=$REDIS_HOST"
ENV_VARS="$ENV_VARS,REDIS_PORT=$REDIS_PORT"
ENV_VARS="$ENV_VARS,REDIS_AUTH_STRING=$REDIS_AUTH_STRING"
ENV_VARS="$ENV_VARS,HUGGINGFACE_API_KEY=$HUGGINGFACE_API_KEY"
ENV_VARS="$ENV_VARS,TOGETHER_API_KEY=$TOGETHER_API_KEY"
ENV_VARS="$ENV_VARS,FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"
ENV_VARS="$ENV_VARS,FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL"
ENV_VARS="$ENV_VARS,FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY"
ENV_VARS="$ENV_VARS,OPENAI_API_KEY=$OPENAI_API_KEY"
ENV_VARS="$ENV_VARS,API_RATE_LIMIT_WINDOW_MS=$API_RATE_LIMIT_WINDOW_MS"
ENV_VARS="$ENV_VARS,API_RATE_LIMIT_MAX_REQUESTS=$API_RATE_LIMIT_MAX_REQUESTS"
ENV_VARS="$ENV_VARS,AI_RATE_LIMIT_WINDOW_MS=$AI_RATE_LIMIT_WINDOW_MS"
ENV_VARS="$ENV_VARS,AI_RATE_LIMIT_MAX_REQUESTS=$AI_RATE_LIMIT_MAX_REQUESTS"
ENV_VARS="$ENV_VARS,CACHE_TTL=$CACHE_TTL"
ENV_VARS="$ENV_VARS,CACHE_NAMESPACE=$CACHE_NAMESPACE"

# Deploy to Cloud Run
gcloud run deploy parenting-assistant-backend \
  --image gcr.io/parentingassistant-9b1cb/parenting-assistant-backend:latest \
  --platform managed \
  --region us-central1 \
  --set-env-vars "$ENV_VARS" | cat 